### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by thanh-tl** [medusajs/nextjs-starter-medusa#106]
Got error when first visit store front 
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/6973796/218004062-108932b3-8236-4ac0-b6eb-da4008314878.png">

Detail log 
```
> medusa-next@1.0.3 dev
> next dev -p 8000

ready - started server on 0.0.0.0:8000, url: http://localhost:8000
info  - Loaded env from /Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/.env.local
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
event - compiled client and server successfully in 2.1s (337 modules)
wait  - compiling...
event - compiled successfully in 241 ms (296 modules)
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 827 ms (937 modules)
Error: No QueryClient set, use QueryClientProvider to set one
    at Object.useQueryClient (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.js:58:11)
    at useHydrate (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/Hydrate.js:30:43)
    at Hydrate (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/Hydrate.js:50:3)
    at processChild (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/next/dist/server/render.js:680:46)
    at Object.defaultGetInitialProps (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/next/dist/server/render.js:350:67)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 149 ms (938 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works
Error: Failed to fetch update manifest Internal Server Error
    at http://localhost:8000/_next/static/chunks/webpack.js?ts=1676004297111:1218:37
wait  - compiling / (client and server)...
event - compiled client and server successfully in 515 ms (945 modules)
error - Error: No QueryClient set, use QueryClientProvider to set one
    at Object.useQueryClient (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.js:58:11)
    at useHydrate (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/Hydrate.js:30:43)
    at Hydrate (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/@tanstack/react-query/build/lib/Hydrate.js:50:3)
    at processChild (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/next/dist/server/render.js:680:46)
    at Object.defaultGetInitialProps (/Users/xxx/xxx/xxx/medusajs/medusa-store/storefront/node_modules/next/dist/server/render.js:350:67) {
  page: '/'
}
```

**Comment by Sl4yZ** [comment]
Same issue here.

**Comment by zorgatia** [comment]
Same issue here.

**Comment by Sl4yZ** [comment]
Fixed by commenting the workaround.
My next.config.js looks like this now : 

`const { withStoreConfig } = require("./store-config")
const store = require("./store.config.json")
const path = require("path")

module.exports = withStoreConfig({
  features: store.features,
  reactStrictMode: true,
  images: {
    domains: ["medusa-public-images.s3.eu-west-1.amazonaws.com", "localhost"],
  },
  // webpack: (config, options) => {
  //   if (options.isServer) {
  //     config.externals = ["@tanstack/react-query", ...config.externals]
  //   }
  //   const reactQuery = path.resolve(require.resolve("@tanstack/react-query"))
  //   config.resolve.alias["@tanstack/react-query"] = reactQuery
  //   return config
  // },
})

console.log("next.config.js", JSON.stringify(module.exports, null, 2))
`
