### ISSUE TITLE
just create new medusa project and it doesnt work

### ISSUE THREAD

**Issue by k0nAtbl4** [medusajs/nextjs-starter-medusa#113]
input:

C:\>cd c:\vajnoe\medusa_app\ura\my-shop\storefront

c:\vajnoe\medusa_app\ura\my-shop\storefront>npm run start

output:
> medusa-next@1.0.3 start
> next start -p 8000

warn  - Invalid casing detected for project dir, received c:\vajnoe\medusa_app\ura\my-shop\storefront actual path C:\vajnoe\medusa_app\ura\my-shop\storefront, see more info here https://nextjs.org/docs/messages/invalid-project-dir-casing
ready - started server on 0.0.0.0:8000, url: http://localhost:8000
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
Error: Could not find a production build in the 'C:\vajnoe\medusa_app\ura\my-shop\storefront\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (c:\vajnoe\medusa_app\ura\my-shop\storefront\node_modules\next\dist\server\next-server.js:169:23)
    at new Server (c:\vajnoe\medusa_app\ura\my-shop\storefront\node_modules\next\dist\server\base-server.js:58:29)
    at new NextNodeServer (c:\vajnoe\medusa_app\ura\my-shop\storefront\node_modules\next\dist\server\next-server.js:70:9)
    at NextServer.createServer (c:\vajnoe\medusa_app\ura\my-shop\storefront\node_modules\next\dist\server\next.js:140:16)
    at async c:\vajnoe\medusa_app\ura\my-shop\storefront\node_modules\next\dist\server\next.js:149:31

c:\vajnoe\medusa_app\ura\my-shop\storefront>next build
warn  - Invalid casing detected for project dir, received c:\vajnoe\medusa_app\ura\my-shop\storefront actual path C:\vajnoe\medusa_app\ura\my-shop\storefront, see more info here https://nextjs.org/docs/messages/invalid-project-dir-casing
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
info  - Linting and checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
unhandledRejection Error: Cannot find module 'next/dist/shared/lib/router/utils/is-local-url.js'
Require stack:
- C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\pages\_app.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\server\require.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\server\load-components.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\export\worker.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\build\worker.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\compiled\jest-worker\processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at mod._resolveFilename (C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 1109 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\pages\_app.js:209:18)
    at __webpack_require__ (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\webpack-runtime.js:25:42)
    at 7760 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\chunks\712.js:1188:19)
    at __webpack_require__ (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\webpack-runtime.js:25:42)
    at 2841 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\chunks\712.js:662:40) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\vajnoe\\medusa_app\\ura\\my-shop\\storefront\\.next\\server\\pages\\_app.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\server\\require.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\export\\worker.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\build\\worker.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\compiled\\jest-worker\\processChild.js'
  ]
}
info  - Collecting page data .
c:\vajnoe\medusa_app\ura\my-shop\storefront>next build
warn  - Invalid casing detected for project dir, received c:\vajnoe\medusa_app\ura\my-shop\storefront actual path C:\vajnoe\medusa_app\ura\my-shop\storefront, see more info here https://nextjs.org/docs/messages/invalid-project-dir-casing
next.config.js {
  "reactStrictMode": true,
  "images": {
    "domains": [
      "medusa-public-images.s3.eu-west-1.amazonaws.com",
      "localhost"
    ]
  },
  "env": {}
}
info  - Linting and checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
unhandledRejection Error: Cannot find module 'next/dist/shared/lib/router/utils/is-local-url.js'
Require stack:
- C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\pages\_app.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\server\require.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\server\load-components.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\export\worker.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\build\worker.js
- C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\compiled\jest-worker\processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at mod._resolveFilename (C:\Users\Константин\AppData\Roaming\npm\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 1109 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\pages\_app.js:209:18)
    at __webpack_require__ (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\webpack-runtime.js:25:42)
    at 7760 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\chunks\712.js:1188:19)
    at __webpack_require__ (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\webpack-runtime.js:25:42)
    at 2841 (C:\vajnoe\medusa_app\ura\my-shop\storefront\.next\server\chunks\712.js:662:40) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\vajnoe\\medusa_app\\ura\\my-shop\\storefront\\.next\\server\\pages\\_app.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\server\\require.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\server\\load-components.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\export\\worker.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\build\\worker.js',
    'C:\\Users\\Константин\\AppData\\Roaming\\npm\\node_modules\\next\\dist\\compiled\\jest-worker\\processChild.js'
  ]
}
info  - Collecting page data .

**Comment by kasperkristensen** [comment]
The command to start the development server is `yarn dev`. Before you can run the start command you need to build the project with `yarn build`
