### ISSUE TITLE
Build Failed TypeError: Cannot set properties of undefined (setting '__definition')

### ISSUE THREAD

**Issue by niioo** [medusajs/nextjs-starter-medusa#192]
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/15)  [    ] ⚠ Entire page /404 deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /404
 ⚠ Entire page /account/profile deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /account/profile
 ⚠ Entire page /account/login deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /account/login
 ⚠ Entire page /account deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /account
 ⚠ Entire page /account/addresses deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /account/addresses
 ⚠ Entire page /account/orders deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /account/orders
 ⚠ Entire page /checkout deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /checkout
   Generating static pages (7/15)  [=   ]
 ⚠ Entire page /store deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /store
Could not resolve module: ProductModuleService. Error: Loaders for module ProductModuleService failed: No database clientUrl provided. Please provide the clientUrl through the [MODULE]_POSTGRES_URL, MEDUSA_POSTGRES_URL or POSTGRES_URL environment variable or the options object in the initialize function.

Error occurred prerendering page "/api/categories". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot set properties of undefined (setting '__definition')
    at MedusaModule.bootstrap (/Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/@medusajs+modules-sdk@1.12.1_graphql@16.8.1/node_modules/@medusajs/modules-sdk/dist/medusa-module.js:124:44)
    at async initialize (/Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/@medusajs+product@0.2.1_graphql@16.8.1_pg@8.11.0/node_modules/@medusajs/product/dist/initialize/index.js:8:20)
    at async GET (/Users/nio/lifease/trash/capilus/capilus/.next/server/app/api/categories/route.js:1:833)
    at async /Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:39709
 ⚠ Entire page /cart deopted into client-side rendering. https://nextjs.org/docs/messages/deopted-into-client-rendering /cart
Could not resolve module: ProductModuleService. Error: Loaders for module ProductModuleService failed: No database clientUrl provided. Please provide the clientUrl through the [MODULE]_POSTGRES_URL, MEDUSA_POSTGRES_URL or POSTGRES_URL environment variable or the options object in the initialize function.

Error occurred prerendering page "/api/collections". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot set properties of undefined (setting '__definition')
    at MedusaModule.bootstrap (/Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/@medusajs+modules-sdk@1.12.1_graphql@16.8.1/node_modules/@medusajs/modules-sdk/dist/medusa-module.js:124:44)
    at async initialize (/Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/@medusajs+product@0.2.1_graphql@16.8.1_pg@8.11.0/node_modules/@medusajs/product/dist/initialize/index.js:8:20)
    at async GET (/Users/nio/lifease/trash/capilus/capilus/.next/server/app/api/collections/route.js:1:833)
    at async /Users/nio/lifease/trash/capilus/capilus/node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:39709
 ✓ Generating static pages (15/15)

**Comment by niioo** [comment]
thanks it worked
