### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map') product/[id].js

### ISSUE THREAD

**Issue by MukundMohanan** [medusajs/nextjs-starter-medusa#21]
Hi, I followed the instruction from [nextjs-medusa-starter](https://docs.medusajs.com/starters/nextjs-medusa-starter) but get the following error when I build the web app.

```
> Build error occurred
TypeError: Cannot read properties of undefined (reading 'map')
    at getStaticPaths (/mnt/c/Users/Project/Medusa/nextjs/Medusa-nextJS/.next/server/pages/product/[id].js:228:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildStaticPaths (/mnt/c/Users/Project/Medusa/nextjs/Medusa-nextJS/node_modules/next/dist/build/utils.js:497:31)
    at async /mnt/c/Users/Project/Medusa/nextjs/Medusa-nextJS/node_modules/next/dist/build/utils.js:640:119
    at async Span.traceAsyncFn (/mnt/c/Users//Project/Medusa/nextjs/Medusa-nextJS/node_modules/next/dist/trace/trace.js:75:20) {
  type: 'TypeError'
}
```
Im running Medusa server on localhost:9000 and is configured the same in .env.local as well
```
✔ Indexing completed – 19ms
✔ Server is ready on port: 9000 – 7ms
::1 - - [19/Mar/2022:07:40:21 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "curl/7.79.1"
::1 - - [19/Mar/2022:07:40:55 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "PostmanRuntime/7.3.0"
::ffff:127.0.0.1 - - [19/Mar/2022:07:47:04 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:07:49:55 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:07:51:38 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:07:53:45 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:07:57:54 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:07:58:35 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::1 - - [19/Mar/2022:08:00:40 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "PostmanRuntime/7.3.0"
::ffff:127.0.0.1 - - [19/Mar/2022:08:00:48 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
::ffff:127.0.0.1 - - [19/Mar/2022:08:00:52 +0000] "GET /store/products HTTP/1.1" 200 59826 "-" "axios/0.21.4"
```

**Comment by kasperkristensen** [comment]
Hi @MukundMohanan, 

So a couple suggestions: 

- You properly already have it running, but just to make sure. You must have your server is running while you are building the Next project, otherwise API calls in getStaticPaths and getStaticProps will fail.
- Try and console.log the API response in getStaticProps so we can get a better idea of what is happening. Just change it so it is no longer destructured, and console.log it then.
