### ISSUE TITLE
"store/regions" endpoint returns: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by volfcan** [medusajs/nextjs-starter-medusa#354]
I've setup the backend and running, specify the .env files accordingly and trying to start the storefront and came across with this error. Any idea on how to fix that?

```typescript
Error [SyntaxError]: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (file:///Users/volfcan/ZedProjects/nextjs-starter-medusa/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096)
    at successSteps (file:///Users/volfcan/ZedProjects/nextjs-starter-medusa/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096)
    at eval (file:///Users/volfcan/ZedProjects/nextjs-starter-medusa/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096)
    at <unknown> (node:internal/process/task_queues:140:7)
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  middleware: true
}

```

**Comment by anh-nguyen-mds** [comment]
same

**Comment by a-bertrand** [comment]
Hello, i solve this by using the correct backend url in .env. I used like a bot the admin url (http://localhost:7001). 

```NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000```

**Comment by kb-0912** [comment]
I got the same problem.

**Comment by VariableVic** [comment]
9 out of 10 times this is due to not providing the correct `MEDUSA_BACKEND_URL`. In local development, it's `http://localhost:9000` by default (no trailing slash).

Please note that in the latest Starter version, `NEXT_PUBLIC_MEDUSA_BACKEND_URL` has been renamed to `MEDUSA_BACKEND_URL` as it's no longer needed to expose it to the client.

Closing this for now, lmk when you're still running into issues.
