### ISSUE TITLE
Can't find Python executable "python" during yarn install

### ISSUE THREAD

**Issue by sergioruizsan** [medusajs/nextjs-starter-medusa#83]
Hi community! While installing the packages, the process stops during the sqlite3 step. Due to I didn't have python installed

```
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @medusajs/medusa@1.5.0" has unmet peer dependency "medusa-interfaces@1.3.3".
warning " > @medusajs/medusa@1.5.0" has unmet peer dependency "typeorm@0.2.x".
warning "@medusajs/medusa > ioredis-mock@5.9.1" has unmet peer dependency "redis-commands@1.x".
warning " > react-instantsearch-hooks-web@6.29.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
warning "react-instantsearch-hooks-web > instantsearch.js@4.42.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
warning "react-instantsearch-hooks-web > react-instantsearch-hooks@6.29.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
warning "react-instantsearch-hooks-web > instantsearch.js > algoliasearch-helper@3.9.0" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
[4/4] 🔨  Building fresh packages...
[-/7] ⠠ waiting...
[6/7] ⠠ cypress
[-/7] ⠠ waiting...
[4/7] ⠠ sqlite3
error /Users/bob/nextjs-starter-medusa/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/bob/nextjs-starter-medusa/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@16.17.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@16.17.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.17.0 | darwin | arm64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@16.17.0 | darwin | arm64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/bob/nextjs-starter-medusa/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/bob/nextjs-starter-medusa/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/bob/nextjs-starter-medusa/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/bob/nextjs-starter-medusa/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/bob/nextjs-starter-medusa/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/bob/nextjs-starter-medusa/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/bob/nextjs-starter-medusa/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:206:21)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/bob/nextjs-starter-medusa/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /Users/bob/nextjs-starter-medusa/node_modules/sqlite3
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/bob/nextjs-starter-medusa/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bob/nextjs-starter-medusa/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/bob/nextjs-starter-medusa/node_modules/sqlite3
node-pre-gyp ERR! node -v v16.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/bob/nextjs-starter-medusa/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/bob/nextjs-starter-medusa/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_
```

**Comment by sergioruizsan** [comment]
SOLVED: Firstly I installed python3 and created the PYTHON env in my `~/.zshrc`. But it looks it does not work with python3, so I installed python 2, and everything worked ok!

Steps are:
* Install python2: https://www.python.org/downloads/release/python-2717/
* check the path of python2 with the command `which python2`
* add the env variable in `~/.zshrc`: `export PYTHON="/usr/local/bin/python2"`
* reload with the command `source ~/.zshrc`
