### ISSUE TITLE
Erro starting  Store front. ReferenceError: window is not defined

### ISSUE THREAD

**Issue by fcheong3b** [medusajs/nextjs-starter-medusa#92]
I have tried to run yarn dev on Node 14, 16, and 18 but I get the same error.

### ReferenceError: window is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.

All the time in the following path.

`storefront/node_modules/@medusajs/medusa-js/dist/index.js:1:93559`

if go to the file and remove the windows used in the line mentioned the store works but then I get an error in the product details page related to the HTTPRqeuter..... (this shouldn't be the way to fix this)

Any idea about this?

**Comment by kasperkristensen** [comment]
Hi @fcheong3b, 

The issue is due to the latest version of `@medusajs/medusa-js`. It has been fixed and will be released later today - https://github.com/medusajs/medusa/pull/3016.

In the mean time you can either downgrade your version of `@medusa/medusa-js` to 1.3.5, or update it to the snapshot mentioned in the PR linked above.

**Comment by fsyntax** [comment]
Hey @kasperkristensen, 

I just updated to the snapshot you mentioned on a Nuxt 3 storefront, followed by this error on the server:
```
[nitro] [dev] [unhandledRejection] Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
at ze (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:42280)
at Je (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:42715)
at t.setHeaders (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:44666)
at t.<anonymous> (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:45375)
at C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:2120
at Object.next (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:2225)
at C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:1162
at new Promise (<anonymous>)
at l (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:907)
at t.request (C:\****\node_modules\.pnpm\@medusajs+medusa-js@1.3.7-snapshot-20230112194226\node_modules\@medusajs\medusa-js\dist\index.js:1:45215)
```

Also in the browser console:

```
Uncaught TypeError: can't access property "custom", bn is undefined - index.js:69:20
```

**Comment by kasperkristensen** [comment]
Thanks for reporting it @fsyntax I'll look into it

**Comment by kasperkristensen** [comment]
Fixed with the release of the latest version of `@medusajs/medusa-js`
